### ISSUE TITLE
from torch._C import *

### ISSUE THREAD

**Issue by TimNekk** [dreamnettech/dreampower#110]
_Traceback (most recent call last):
  File "main.py", line 9, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "argv\__init__.py", line 9, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "argv\daemon.py", line 3, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "daemon.py", line 11, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "processing\folder.py", line 11, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "processing\utils.py", line 5, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "transform\gan\__init__.py", line 5, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: Операционная система не может запустить %1.
[9352] Failed to execute script main_

**Got this error 01.02, but it was working a day before...**

**I am using conda 4.9.2**

**conda list**
https://pastebin.com/rNbeS7Lu

**Comment by kolessios** [comment]
For people looking for the same error: For some reason the version of PyTorch in the latest version of DreamPower may conflict with the `C:\Windows\System32\libiomp5md.dll` file in Windows, it is a common problem and there is no information on why this occurs. The simplest solution is to delete the file in question.
