### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by hypnoai** [dreamnettech/dreampower#77]
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    argv.run()
  File "/content/dreampower/argv/__init__.py", line 35, in run
    args.func(args)
  File "/content/dreampower/main.py", line 25, in main
    select_processing().run()
  File "/content/dreampower/processing/__init__.py", line 23, in run
    r = self._execute(*args)
  File "/content/dreampower/processing/image.py", line 60, in _execute
    r = run_worker(p, self.__image_steps, config=self._args)
  File "/content/dreampower/processing/worker.py", line 49, in run_worker
    r = w.run(*[image_step[i] for i in w.input_index], config=config)
  File "/content/dreampower/transform/__init__.py", line 26, in run
    return super().run(*args, config=config)
  File "/content/dreampower/processing/__init__.py", line 23, in run
    r = self._execute(*args)
  File "/content/dreampower/transform/opencv/mask.py", line 107, in _execute
    bodypart_list = extract_annotations(args[1], enable_pubes)
  File "/content/dreampower/transform/opencv/bodypart/extract.py", line 19, in extract_annotations
    tits_list = find_body_part(maskdet, "tit")
  File "/content/dreampower/transform/opencv/bodypart/extract.py", line 64, in find_body_part
    contours, _ = cv2.findContours(color_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)

**Comment by hypnoai** [comment]
Sorry my fault. I was making it work in Google Colab and I was far too creative in my approach that I forgot to install the requirements.txt (with the one in later commits containing exact versions specified). 

Many thanks
