### ISSUE TITLE
Transformation #1 failed

### ISSUE THREAD

**Issue by migotsai0819** [dreamnettech/dreampower#80]
The process has been interrupted by an unknown error, this may be caused by a corrupt installation, please check the console for more information.

For more information please take a screenshot and report the following on Github or here:

        Error: [INFO] Welcome to DreamPower
[INFO] GAN Processing Will Use GPU IDs: [0]

[INFO] Executing Image Processing [INFO] Processing on C:\Users\Eric Tsai.LAPTOP-PEHSU7T7\Desktop/1566161344440605.jpg

[INFO] Executing Image To Crop [INFO] Executing Image To Resized

Traceback (most recent call last): File "main.py", line 82, in <module> File "argv_init__.py", line 35, in run File "main.py", line 25, in main File "processing_init.py", line 23, in run File "processing\image.py", line 78, in execute File "processing\worker.py", line 49, in runworker File "transform__init.py", line 26, in run File "processing_init__.py", line 23, in run File "transform\opencv\resize.py", line 76, in execute

File "transform\opencv\resize.py", line 83, in calculatenew_size ZeroDivisionError: float division by zero [4960] Failed to execute script main

**Comment by migotsai0819** [comment]
[INFO] Welcome to DreamPower [INFO] GAN Processing Will Use GPU IDs: [0]

[INFO] Executing Image Processing [INFO] Processing on C:\Users\Eric Tsai.LAPTOP-PEHSU7T7\Desktop/1566161344440605.jpg

[INFO] Executing Image To Crop [INFO] Executing Image To Resized

Traceback (most recent call last): File "main.py", line 82, in <module> File "argv_init__.py", line 35, in run File "main.py", line 25, in main File "processing_init.py", line 23, in run File "processing\image.py", line 78, in execute File "processing\worker.py", line 49, in runworker File "transform__init.py", line 26, in run File "processing_init__.py", line 23, in run File "transform\opencv\resize.py", line 76, in execute File "transform\opencv\resize.py", line 83, in calculatenew_size ZeroDivisionError: float division by zero [12256] Failed to execute script main

**Comment by deeppppp** [comment]
can yo provide the size of the input image, and the parameters given to dreampower?
