### ISSUE TITLE
--ignore-size error

### ISSUE THREAD

**Issue by TravisScottex** [dreamnettech/dreampower#93]
Ubuntu 16, all work but no ignore size parameter

[INFO] Executing Mask To Maskref
Traceback (most recent call last):
  File "DeepNude/main.py", line 82, in <module>
    argv.run()
  File "/var/www/html/.../.../argv/__init__.py", line 35, in run
    args.func(args)
  File "/var/www/html/.../.../main.py", line 25, in main
    select_processing().run()
  File "/var/www/html/.../.../processing/__init__.py", line 23, in run
    r = self._execute(*args)
  File "/var/www/html/.../.../processing/image.py", line 96, in _execute
    r = run_worker(p, self.__image_steps, config=self._args)
  File "/var/www/html/.../.../processing/worker.py", line 49, in run_worker
    r = w.run(*[image_step[i] for i in w.input_index], config=config)
  File "/var/www/html/.../.../transform/__init__.py", line 26, in run
    return super().run(*args, config=config)
  File "/var/www/html/.../.../processing/__init__.py", line 23, in run
    r = self._execute(*args)
  File "/var/www/html/.../.../transform/opencv/mask.py", line 55, in _execute
    res2 = cv2.bitwise_and(green, green, mask=green_mask)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/core/src/arithm.cpp:250: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'binary_op'

**Comment by kolessios** [comment]
Sorry for the late reply, the `--ignore-resize` parameter is not recommended to use unless you know what you are doing. The algorithm obligatorily requires that the photos be of dimensions 512x512 otherwise the above error occurs.
